services:
  - type: web
    plan: free
    name: flask-sample
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --config src/gconfig.py 'src.app:app'"
    envVars:
      - key: GUNICORN_BIND
        value: "0.0.0.0:8000"